title: hexo-renderers documentation
subtitle: All in one shortcodes for hexo
description: All in one collection shortcodes for hexo
author: Dimas Lanjaka
keywords: null
language: en
timezone: Asia/Jakarta
url: https://www.webmanajemen.com/docs/hexo-renderers
root: /docs/hexo-renderers/
permalink: :title.html
permalink_defaults: null
pretty_urls:
  trailing_index: true
  trailing_html: true
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render: null
new_post_name: :title.md
default_layout: post
titlecase: false
external_link:
  enable: true
  field: site
  exclude:
    - webmanajemen.com
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
highlight:
  enable: false
  line_number: true
  auto_detect: false
  tab_replace: "  "
  wrap: false
  hljs: true
prismjs:
  enable: true
  preprocess: true
  line_number: true
  line_threshold: 0
  tab_replace: ""
index_generator:
  path: ""
  per_page: 10
  order_by: -date
default_category: uncategorized
category_map: null
tag_map: null
meta_generator: true
date_format: YYYY-MM-DD
time_format: HH:mm:ss
updated_option: mtime
per_page: 10
pagination_dir: page
include: null
exclude: null
ignore: null
theme: butterfly
markdown:
  preset: default
  render:
    html: true
    xhtmlOut: false
    langPrefix: language-
    breaks: true
    linkify: true
    typographer: true
    quotes: “”‘’
  enable_rules: null
  disable_rules: null
  plugins: null
  anchors:
    level: 2
    collisionSuffix: ""
    permalink: false
    permalinkClass: header-anchor
    permalinkSide: left
    permalinkSymbol: ¶
    case: 0
    separator: "-"
deploy:
  type: ""
browsersync:
  logLevel: warn
  ghostMode:
    scroll: true
  instanceName: uniqueString
seo:
  html:
    enable: true
    fix: true
    exclude:
      - "*.min.{htm,html}"
  css:
    enable: true
    exclude:
      - "**/*.min.css"
  js:
    enable: true
    exclude:
      - "**/*.min.js"
    options:
      compress:
        dead_code: true
      mangle:
        toplevel: true
        safari10: true
  schema:
    article:
      enable: true
    breadcrumb:
      enable: true
    sitelink:
      enable: true
      searchUrl: https://www.webmanajemen.com/hexo-seo/search?q=
  img:
    enable: true
    broken: false
    default: https://upload.wikimedia.org/wikipedia/commons/6/65/No-Image-Placeholder.svg
    onerror: clientside
  links:
    enable: true
    exclude:
      - webmanajemen.com
      - web-manajemen.blogspot.com
  sitemap: true
