# https://github.com/jerryc127/hexo-theme-butterfly/blob/dev/_config.yml

menu:
  Home: / || fas fa-home
  List||fas fa-list:
    Page with custom layout: /page-with-custom-layout.html || fas fa-music
  #   Movie: /movies/ || fas fa-video